remote_theme: coursweb/jk-theme
title: WordPress (New)
description: Un support de cours WordPress gratuit et open-source.
lang: fr-FR
chapters:
 - title: Cours-web
   url: https://cours-web.ch/
 - title: WordPress (New)
   url: https://cours-web.ch/wp-new/   
 - title: HTML
   url: https://cours-web.ch/html/
 - title: CSS
   url: https://cours-web.ch/css/
 - title: JavaScript
   url: https://cours-web.ch/javascript/
 - title: Serveurs
   url: https://cours-web.ch/serveurs/
 - title: WordPress (Old)
   url: https://cours-web.ch/wp/